### ISSUE TITLE
Creación del cliente para el nuevo resoluciones.

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente_v2#1]
Registrar la creación y ajustes asociados al nuevo repositorio del cliente de resoluciones.

**Criterios de aceptación**

- [x]  Creación y ajustes del cliente.

**Comment by jupmorenor** [comment]
Se realiza un clon del cliente de Alternancia y se usa como base para la creación del nuevo cliente para Resoluciones. En este clon, se reemplaza la palabra **alternancia** por la palabra **resoluciones**, así mismo se reemplazan las referencias a **alternancia_cliente** por **resoluciones_cliente_v2**.
Con solo estos cambios se logra que al iniciar el cliente se muestre con la apariencia correspondiente para este sistema gracias a la configuración de webcomponents.

![image](https://user-images.githubusercontent.com/11802554/141200120-e35de0f4-cca7-4d3a-9eaf-9c1de886c447.png)

Se encontró que el cliente de Alternancia tenía agregada manualmente la información del menú, al retirar estos datos se encuentra que el menú es cargado correctamente desde la api de configuración sin necesidad de hacer mayores cambios.

![image](https://user-images.githubusercontent.com/11802554/141200269-a0166b9b-aa6e-4020-b098-93ab5969c89e.png)
