### ISSUE TITLE
Desarrollo módulo de expedición de resoluciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente_v2#10]
Desarrollar las funcionalidades asociadas al modulo de expedición de resoluciones para el nuevo resoluciones.

**Criterio de aceptación**

- [x] Commit en rama feat con cambios realizados para API MID.
- [x] Commit en rama feat con cambios realizados para el Cliente.
- [x] Pruebas Unitarias.
- [x] Pruebas Funcionales.
- [x] Despliegue en ambiente de pruebas

**Comment by Yaov05** [comment]
El desarrollo se había visto retrasado debido a que existen peticiones a apis que actualmente se encuentran deprecadas como el caso de Kronos. 

En específico, el módulo de expedición de resoluciones realiza una petición para la disponibilidad, siendo el endpoint:

/disponibilidad_apropiacion/

Se citó una reunión para aclarar si se reemplazan estos endpoints para obtener la información necesaria, y se continúa trabajando en el desarrollo de otros módulos mientras se logra aclarar esta parte.
