### ISSUE TITLE
Corrección de hallazgos en ambiente de producción

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#100]
Revisar y corregir los siguientes hallazgos:

- [x] Registro de menú y configuración del mismo.
- [x] Configurar control de acceso.
- [x] Revisar asignación de roles al usuario pruebasoas2.
- [x] Verificar cálculo por semanas en contratación docente (evitar hacer cálculo por meses).

**Comment by jupmorenor** [comment]
Se revisaron los componentes del menú y se registró el control de acceso en la aplicación de configuración. OK
