### ISSUE TITLE
Modelo plantilla de resolución

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#102]
- [x] Con el propósito de dar por validada la plantilla de una resolución expedida por el sistema, adjuntar al issue un ejemplo de como las está generando el sistema.

**Comment by jupmorenor** [comment]
Se genera una resolución de muestra en la que puede visualizarse el formato utilizado para el cuadro de vinculaciones que incluye el valor del contrato desagregado por rubros presupuestales.

[Resolución de muestra Vinculación HCP.pdf](https://github.com/udistrital/resoluciones_cliente_v2/files/10322837/Resolucion.de.muestra.Vinculacion.HCP.pdf)
