### ISSUE TITLE
Revisión y validación de documentación

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#103]
- [x] Revisar documentación de resoluciones v1 y adaptarlo
- [x] Revisar los videotutoriales elaborados por Rony encontrados en: https://drive.google.com/drive/u/1/folders/1-yJUg2p7Yn2OiRqs4YocKH0rhao4BWDj

Elaborar vídeos sobre nuevas funcionalidades:
- [x] RP.
- [x] Copia o duplicado de plantilla.

**Comment by jupmorenor** [comment]
Se hizo revisión de los videotutoriales existentes y teniendo en cuenta las mejoras que se le han hecho al sistema después de la elaboración de los videos, se sugiere rehacerlos todos para incluir en las imágenes estas mejoras.

**Comment by jupmorenor** [comment]
Se elaboraron pequeños videos con la explicación de las funcionalidades nuevas:

- Copia de plantillas
- Filtros de búsqueda
- Asignación de Registros presupuestales

**Comment by jupmorenor** [comment]
Se realiza revisión y actualización del manual de usuario de la versión anterior del Modulo de Resoluciones con las características de la nueva versión del sistema: [Link al documento](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/jupmorenor_udistrital_edu_co/EW_s8bCIg19NmDiA8F5-6i0BcfUMjSaP0w1CPBLP0E1CpQ?e=uoLuug)
