### ISSUE TITLE
Cambio de vigencia

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#104]
- [x] Aplicar cambio de vigencia con base en la construcción de reglas que se encuentra en el ruler.

**Comment by jupmorenor** [comment]
Se realiza solicitud de ejecución de script generado a traves de [KB51131](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=51131&group_id=177) luego de evaluar la información en la base de datos e identificar las reglas que requieren ser replicadas para la vigencia 2023

**Comment by jupmorenor** [comment]
Se está validando que los sistemas involucrados funcionen correctamente con la aplicación del script del KB en ambiente de pruebas.

**Comment by jupmorenor** [comment]
Se ha validado que todo funciona correctamente en ambiente de pruebas y se ha ejecutado ahora en producción.
