### ISSUE TITLE
Revisión de APIs a ser depreciadas o migradas

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#107]
Con base en la experiencia de desarrollo en la oficina, relacionar APIs que consideras deben ser migradas o depreciadas en el siguiente documento.

https://docs.google.com/spreadsheets/d/1NUGxIB2OFe56SNgtihhYNh7kEFRblh9u2lsuNtxIV_k/edit#gid=0

**Comment by jupmorenor** [comment]
Se ha registrado la información correspondiente a las APIs que pueden ser depreciadas teniendo en cuenta el cambio de versión del Modulo de Resoluciones en el documento enlazado arriba.
