### ISSUE TITLE
Depliegue a producción posterior a hallazgos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#109]
Se requiere listar los elementos necesarios para salir a producción con las APIs del sistema y el cliente, así como registrar la trazabilidad de las solicitudes que se realicen.

Se despliega en producción el desarrollo asociado a la corrección de hallazgos resultantes de pruebas piloto.

Criterios de aceptación

- [x]  Checklist de salida a producción por cada API y el cliente.
- [x]  Trazabilidad de peticiones y commits para salida a producción.
- [x]  Estabilización del sistema en producción.

**_**Nota: Tomar como ejemplo los checklist utilizados con anterioridad https://github.com/udistrital/resoluciones_cliente_v2/issues/68**_**

**Comment by jupmorenor** [comment]
Se elaboran documentos checklist para salida a producción:

[Resoluciones Cliente v2](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/jupmorenor_udistrital_edu_co/EeLJZn-u3Y5Ei8-aH0acYekByE2jfSil5PYmyeoC3dqe5g?email=cerochac%40udistrital.edu.co&e=qdUIaL)
[Resoluciones MID v2](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/jupmorenor_udistrital_edu_co/EXsgNI1WWCBDuM5n37BK4mUBnkjdlplTFkoHg-WflRZb9Q?email=cerochac%40udistrital.edu.co&e=VUVfAO)
Resolucones CRUD v2 no tuvo cambios

**Comment by jupmorenor** [comment]
El sistema se encuentra estable en ambiente de producción
