### ISSUE TITLE
Plantillas de resoluciones v2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#110]
Adjuntar a este issue resoluciones ejemplo de tipo:

- [x] Adición
- [x] Reducción
- [x] Cancelación

**Comment by jupmorenor** [comment]
Se generan resoluciones de muestra en las que puede visualizarse el formato utilizado para el cuadro de vinculaciones que incluye el valor del contrato desagregado por rubros presupuestales, detallando el valor anterior de la vinculación, el valor de la modificación realizada (sea adición, reducción o cancelación) y el valor final de la vinculación al aplicarle la modificación.
Cabe aclarar que estos formatos NO se van a aplicar al proceso de contratación docente del periodo académico 2023-I que ya está en curso.

[resolución de muestra Adición HCP.pdf](https://github.com/udistrital/resoluciones_cliente_v2/files/10468183/resolucion.de.muestra.Adicion.HCP.pdf)
[resolución de muestra Reducción HCP.pdf](https://github.com/udistrital/resoluciones_cliente_v2/files/10468182/resolucion.de.muestra.Reduccion.HCP.pdf)
[resolución de muestra Cancelación HCP.pdf](https://github.com/udistrital/resoluciones_cliente_v2/files/10468184/resolucion.de.muestra.Cancelacion.HCP.pdf)
