### ISSUE TITLE
Pruebas funcionales interoperabilidad con titán

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#113]
Realizar pruebas funcionales referentes a la interoperabilidad con titán al:

- [x] Añadir RP para vinculaciones y adiciones
- [x] Expedir una anulación (cancelación)

**Criterios de aceptación**

- [x] Pruebas funcionales asociadas a las tres novedades.
- [x] Formato de hallazgos.

**Comment by jupmorenor** [comment]
Se realizaron pruebas funcionales sobre la interoperabilidad con Titan, se adjuntan hallazgos:
[Hallazgos interoperabilidad con Titan](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/jupmorenor_udistrital_edu_co/ETXWSOgQxmtLjvB2tKeQ_F0Baa07V3V1RjQzitm1ksM8ag?e=KumSMP)
Estos hallazgos ya fueron corregidos en #108
