### ISSUE TITLE
Revisión de fechas en las resoluciones

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#117]
- [x] Revisión de fecha final de anulaciones teniendo en cuenta que el cálculo es por semanas.
- [x] Ajustar el tipo de dato a string en el artributo "fecha_inicio" de la tabla "vinculacion_docente".

**Comment by jupmorenor** [comment]
Se hizo análisis sobre los calendarios académicos de diferentes periodos académicos en varios años para observar las particularidades con respecto a la fecha de inicio y la fecha de fin de las actividades académicas. A partir de este análisis, se realizaron ajustes sobre el algoritmo que calcula la fecha de fin de las vinculaciones de manera que se garantice que estas siempre terminen a final de semana, con esto, se asegura que los cálculos y las fechas generadas por el sistema sean consistentes en los diferentes tipos de resolución.
 
![image](https://user-images.githubusercontent.com/11802554/215622165-91458bef-4f89-410c-898c-1381b69e6ef5.png)

Se generaron vinculaciones por 18 semanas a partir del 01-02-2023 quedando con fecha de fin el 10-06-2023 coincidiendo con lo establecido por el calendario académico:
![image](https://user-images.githubusercontent.com/11802554/215622790-db2ff3a6-1d4e-46aa-8ee1-a9eddac7b9f4.png)

Posteriormente, se realizó prueba de cancelación para una de estas vinculaciones por 11 semanas, quedando la vinculación con 7 semanas y fecha de fin 24-03-2023
![image](https://user-images.githubusercontent.com/11802554/215622999-13275692-9c85-491a-81cf-858ce63779fc.png)
