### ISSUE TITLE
Ajustes de interoperabilidad con Titán

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#118]
- [x] En anulaciones (Cancelaciones), ajustar el body que se envía en la petición a titan para la preliquidación, para que se incluya el valor total del contrato.
- [x] Implementar el llamado al endpoint de preliquidación de reducciones de titán, al momento de expedir una resolución de este tipo.

**Comment by jupmorenor** [comment]
Se realiza análisis del proceso de reducción incluyendo los casos especiales de manera general, a partir de este análisis se desarrolló la funcionalidad de interoperabilidad donde se tiene en cuenta el cálculo del desagregado para el contrato reducido.
![image](https://user-images.githubusercontent.com/11802554/217127719-250c243e-e059-47d8-a067-8b6dc6004e20.png)
