### ISSUE TITLE
Pruebas de interoperabilidad con titán

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#119]
Realizar pruebas funcionales referentes a la interoperabilidad con titán al expedir una resolución de reducción con los siguientes casos:

- [x] Vinculación - Reducción
- [x] Vinculación - Adición - Reducción
- [x] Vinculación - Adición - Adición - Adición - Reducción
- [x] Vinculación - Adición - Reducción - Adición - Reducción.

**Criterios de Aceptación**

- [x] Pruebas funcionales asociadas a las tres novedades.
- [x] Formato de hallazgos.

**Comment by jupmorenor** [comment]
Se realizaron las pruebas funcionales mencionadas sobre la interoperabilidad con titan, se realizaron las correcciones pertinentes para corregir los hallazgos, estos se registraron en el [documento de hallazgos](https://docs.google.com/spreadsheets/d/1wEz5oF0_IG_uV9NvsCT1Emh-uxqf8666/edit?usp=share_link&ouid=115705338596905688240&rtpof=true&sd=true)
