### ISSUE TITLE
Documento Diagnóstico Resoluciones v2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#120]
Teniendo en cuenta la finalización de la contratación realizar un documento dónde se evidencie:

- [x] El estado actual del sistema
- [x] Bugs, errores conocidos y deuda técnica
- [x] Limitaciones
- [x] Actividades realizadas para salir a producción – Equipo de desarrollo
- [x] Actividades requeridas para salir a producción – Equipo de desarrollo
- [x] Actividades requeridas para salir a producción – Terceros
- [x] Usuarios de prueba – WSO2
- [x] Videotutoriales y Manuales de usuario
- [x] Plan de mejoramiento

**Comment by jupmorenor** [comment]
Se redacta [documento de diagnóstico final del Modulo de Resoluciones v2](https://docs.google.com/document/d/1McpWczFJC5AFfokV-iisiZkgWXaeXDKE/edit?usp=share_link&ouid=115705338596905688240&rtpof=true&sd=true)
