### ISSUE TITLE
Adaptación y definición de parametrización de fechas resoluciones v2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#124]
Teniendo en cuenta la inducción realizada con Juan Pablo [inducción](https://udistritaleduco-my.sharepoint.com/:f:/r/personal/cerochac_udistrital_edu_co/Documents/Trabajo%20OAS/2023/Resoluciones%20V2?csf=1&web=1&e=hOOUlw), bajar cada uno de los repositorios asociados al sistema de resoluciones v2 (Cliente, mid y crud) y montarlos en un ambiente local, para comprender la parametrización de fechas de resoluciones y su interacción con titan y Argo.

**Especificaciones técnicas**

- Clonar los repositorios de resoluciones v2 en local.
- Determinar el manejo actual de fechas de resoluciones de vinculación, adición, reducción y cancelación.
- Establecer correlación de datos con apis de titan y Agora o Argo.

**Sub Tareas**

- [x] Clonar los repositorios.
- [x] Parametrizar en un comentario del issue como se están tratando las fechas en las resoluciones de cada tipo (vinculación, adición, reducción y cancelación)
- [x] Definir si se manejan las fechas de igual manera en Argo/Agora, resoluciones v2 y titán.

**Criterios de aceptación**

- [x] Comentario del issue con la parametrización de fechas de todos los tipos de resoluciones.
- [x] Comentario del issue que relacione como se manejan las fechas en Argo/Agora y titán.
- [x] En dado caso de tener diferencia de manejo de fechas entre los sistemas colocar los respectivos comentarios. 

**Requerimientos**

- [x] Ninguna

**Dependencias**

- Argo
- Agora
- Titán

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Comment by diagutierrezro** [comment]
**Nota:**  Inicialmente me doy cuenta que las funcionalidades realizadas para interoperabilidad con Titan no se encuentran en ambiente de pruebas, unicamente en local

**Manejo de las fechas:** 

- Tanto en la vinculación como en la adición se usa una formula para calculo de fechas en la que si la resolución inicia a mitad de semana o mas se hace un ajuste para que esta finalice el sabado de la ultima semana de la resolución. Por ejemplo si una resolución de 16 semanas inicia el 1 de febrero de 2023 (miercoles) se realiza el ajuste para terminar el sabado de la ultima semana de la resolución (27 de mayo de 2023), estas dos fechas son enviadas en un desagregado hacia titan para realizar la preliquidación.

Formula para calculo de fechas
![image](https://user-images.githubusercontent.com/38676533/236045175-2b980af2-e9d7-44bf-994d-bcd9a03610d0.png)

Ejemplo de registros de fechas en Titan
![image](https://user-images.githubusercontent.com/38676533/236046249-a5712e74-3b88-4939-b9c7-e33fde78ee6d.png)

**Comment by diagutierrezro** [comment]
La interoperabilidad con titan para las novedades de reducción y cancelación no están funcionando correctamente.

**Comment by diagutierrezro** [comment]
Se realizan pruebas con diferentes combinaciones de novedades en las resoluciones, se evidencia que las resoluciones de vinculación y adición funcionan correctamente.

Queda pendiente por revisar un error en la reducción ya que en la resolución registraun valor y en Titan se registró otro valor menor. Adicional a esto se debe realizar una prueba mas exhaustiva de las novedades de cancelación para definir si esta funciona correctamente.
