### ISSUE TITLE
Despliegue de interoperabilidad con titán en ambiente de pruebas

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#125]
Desplegar feature de interoperabilidad en titan y resoluciones.

**Especificaciones técnicas**

- Desplegar en release la interoperabilidad en titán y resoluciones que se encuentra en la feature/interop_titan.

**Sub Tareas**

- [x] Despliegue en release de interoperabilidad en resoluciones v2.
- [x] Despliegue en release de interoperabilidad en titan_api_mid.

**Criterios de aceptación**

- [x] Prueba de interoperabilidad en ambiente de pruebas, comentarla en el issue.

**Requerimientos**

- Ninguna

**Dependencias**

- Titán

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se realizan los respectivos PR a develop y posteriormente a release de las dos APIs (titan_api_mid y resoluciones_mid).

Posteriormente se realizan pruebas basicas de las resoluciones como vinculación o adiciones para comprobar que estas dos APIs se encuentren interoperando correctamente entre si.
