### ISSUE TITLE
Ajuste de endpoint de reduciones en titán

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#126]
Revisar el servicio asociado a reducciones desarrollado en titán dado que se presenta un error al calcular las preliquidaciones posterior al generar una reducción.

**Especificaciones técnicas**

- Revisar en titan_api_mid el servicio de reducciones ya desplegado en pruebas.
- Corregir el cálculo de valores en las preliquidaciones.

**Sub Tareas**

- [x] Corregir comportamiento del servicio en titan_api_mid.
- [x] Probar localmente la corrección al cálculo
- [x] Desplegar en release.

**Criterios de aceptación**

- [x] Comentario del issue con el error presentado y la solución propuesta
- [x] Comentario del issue con las pruebas locales realizadas

**Requerimientos**

- [x] Ninguna

**Dependencias**

- Titán

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Este error ocurría cuando se aplicaba una reducción en el mismo mes de inicio de algún contrato ya que en estos casos en Titan se maneja como una cancelación seguida de una preliquidación nueva, en estos casos se leía el valor de un detalle_preliquidación de la base de datos y se le estaba restando al valor del salario base del contrato que se reducia

**Comment by diagutierrezro** [comment]
![image](https://github.com/udistrital/resoluciones_cliente_v2/assets/38676533/20afeca1-de22-43d1-98b9-ed12457fb3e9)
Se adjunta una imagen de los registros que se almacenan en titan despues de realizar una vinculación - adición y posteriormente una reducción en el mismo mes de inicio de la adición que era donde se generaba el error. Allí se puede evidenciar que al sumar los valores de los contratos que tienen el campo activo en **true** coincide con la suma de los valores de los contratos generales que representan el valor total que se le paga al docente o contratista dicho mes.
