### ISSUE TITLE
Despliegue a producción

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#128]
Se requiere realizar la salida a producción de todas las funcionalidades desarrolladas en Resoluciones v2 a la fecha, relacionadas con el MVP, teniendo en cuenta los siguientes requerimientos:

**Definition of Done - DoD - Despliegues**

- [x] Aprobación Gerente de Proyectos: no obligatorio Hotfix, Bugfix
- [x] Aprobación Funcionamiento
- [x] Actualización de Swagger en WSO2 
- [x] Revisión y actualización de variables de entorno
- [x] Pruebas funcionales (grupo de soporte)
- [x] Pruebas de carga, estrés y seguridad (líder de seguridad)
- [x] Pruebas de usuario (Preguntar Revisión SIGUD)
- [x] Pruebas unitarias (equipo de desarrollo)
- [x] Cargue de plantillas en v2
- [x] Revisión de sincronización de bases de datos en ambientes (prueba y producción)
- [x] Revisión de estado de bases de datos (ETL)
- [x] Revisión de actualización de APIs consumidas (terceros, transversales)
- [x] Definición y/o actualización de manual de usuario/videotutoriales
- [x] Documento técnico - D

**Comment by milo19980525** [comment]
Ejemplo de manual técnico: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/daarojasg_udistrital_edu_co/ETpqKLRaJ0FOuVrphRqieo0BMKQfKNKUQZOrRpTZqgZS1g?e=nwJfZ8

**Comment by milo19980525** [comment]
El día 6 de julio, se realiza socialización por segunda vez con las decanaturas y financiera, dónde se presentan diferencias frente al proceso de expedición de RP's con el reporte sugerido, tanto en pregrado pero más acentuado en posgrado.

**Comment by milo19980525** [comment]
El día 7 de julio se expone el sistema frente al soporte de primer y segundo nivel, el arquitecto y el gerente de proyectos. Se concluye que el sistema permite realizar la discriminación por proyecto curricular - RP, por lo que se debe revisar con decanaturas que proceso se debe llevar a cabo. En dado caso de que el RP sea discriminado por RP, se debe realizar ajuste en consulta de RP (busservicios) y verificar el proceso de preliquidación (vinculación y adición).

**Comment by milo19980525** [comment]
Se verificaron variables de entorno y están actualizadas.

**Comment by diagutierrezro** [comment]
Se crea el [documento ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/Efy4f1GD7VBKnb_pKH-z-ZUBSICfm5fIgJtGSiduPn9Msg?e=TcACjk) con la descripción tecnica del sistema

**Comment by milo19980525** [comment]
Gestión de resoluciones - https://youtu.be/ThVonSWaLbo
Aprobación de resoluciones V2 - https://youtu.be/JW8skIvsLq8
Administrador de Resoluciones V2 - https://youtu.be/XteGm4iIvHo
Gestión de plantillas V2 - https://youtu.be/WjiqVo28iZM
Gestión de resoluciones V2 - https://youtu.be/WOhCY_94cA0

Manual: https://tinyurl.com/mvedhksb

**Comment by diagutierrezro** [comment]
![image](https://github.com/udistrital/resoluciones_cliente_v2/assets/38676533/e825c0c1-7e48-4d5b-8424-f37b869385c6)
Se realiza el despliegue a producción del sistema de resoluciones V2 exitosamente

**Comment by diagutierrezro** [comment]
Se deben definir los roles en producción para restringir los respectivos menus.

**Comment by milo19980525** [comment]
Se definieron los roles con base en las respuestas de las decanaturas quedando así:

Decano: acceso a todos los menús excepto a "reporte financiera"
Asistente_decanatura: Acceso a plantillas y gestion de resoluciones
Asis_financiera: Acceso a reporte financiera

**Comment by milo19980525** [comment]
Se actualiza documento técnico: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EZ6RCbNX1AVDqg2MXTRhG4oBmuJMzx2AZQ7EytUxV6r6Jw?e=Kbqexr
