### ISSUE TITLE
Correcciones posteriores a pruebas

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#129]
Realizar los ajustes necesarios para que el sistema quede funcional y listo para desplegar.

**Especificaciones técnicas**

- Revisar y corregir las cancelaciones con docentes dve en posgrado.
- Revisar la estimación de fechas y encontrar una solución para que en titán queden bien las semanas y en resoluciones las fechas.
- Revisar y corregir el calculo de reducciones en HCH.
- Revisar y corregir cancelaciones HCS y HCH.
- Revisar cálculo de contratos generales (MTO - TCO).
- Revisar cálculo que se envía a titan para docentes con un RP, una resolución y un mismo proyecto curricular.
- Dejar campo dinámico de fechas en las resoluciones de vinculación.
- Restricción de otras resoluciones en otros caminos (proyectos curriculares) para que no permita incrementos.
- Agregar filtro de proyecto curricular en la selección de docentes en resoluciones de (Adición, reducción y cancelación)
- Dejar en el manual el comentario sobre las reducciones (Ej. -5) - reducciones a 0 o menores para reducir sobre otro rp.

**Sub Tareas**

- [x] Corregir cálculo de valores en los contratos en titán cuándo las cancelaciones de los docentes DVE tienen más horas pagadas que las reducidas.
- [x] Corregir una cancelación que afecta más de un contrato HCS.
- [x] Corregir una reducción que afecta más de un contrato HCH.
- [x] Ajustar el manejo de fechas en resoluciones y hacía titán para que queden reales en resoluciones (bajo unos lineamientos) y en titán con la cantidad de semanas.
- [x] Revisar cálculo de contratos generales en HCS (TCO y MTO).
- [x] Corrección de cálculo de contrato mes dependiente a un RP, resolución.
- [x] Presentar filtro por proyecto curricular en las resolciones.
- [x] Usar campo dinámico en la resolución para la fecha de vinculación (inicial y final).
- [x] Probar localmente la corrección al cálculo y el manejo de fechas.
- [x] Mostrar todos los RP a afectar en una reducción que tenga 2 o más Adiciones relacionadas.
- [x] Cambiar cálculo de meses a semanas.
- [x] Agregar atributo "Resolución" en titán.
- [x] Desplegar en release.

**Criterios de aceptación**

- [x] Comentario del issue con los errores presentados y las soluciones propuestas
- [x] Comentario del issue con las pruebas locales realizadas

**Requerimientos**

- [x] Ninguna

**Dependencias**

- Titán

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se dejan como evidencia resoluciones de vinculación que se encuentra nen producción para ver el manejo de fechas que se dan en estas
[resolución producción ejemplo.pdf](https://github.com/udistrital/resoluciones_cliente_v2/files/11520428/resolucion.produccion.ejemplo.pdf)
[resolución vinculación producción.pdf](https://github.com/udistrital/resoluciones_cliente_v2/files/11520436/resolucion.vinculacion.produccion.pdf)

**Comment by diagutierrezro** [comment]
Se realiza una reunión con uno de los usuarios debido a unas inquietudes sobre como se manejarán las novedades de reducción y cancelación en POSGRADO, se define lo siguiente:

- **Reducción:** Por las particularidades que tienen los docentes de posgrado en el que no manejan la misma cantidad de horas semanales se hace necesario que el usuario que realiza la resolución indique la cantidad de horas a reducir y la cantidad de horas que ya han sido trabajadas para poder realizar los calculos correctamente en el sistema Titan.
- **Cancelación:** Debido a lo acordad anteriormente en donde una resolución de cancelación debe cancelar todas las vinculaciones que se encuentren asociadas al mismo RP se debe indicar las horas a cancelar de cada una de las vinculaciones extra que tenga el docente con el mismo RP ya que actualmente para una cancelación al sistema solo se le indica una cantidad de horas a cancelar para todas las vinculaciones.
