### ISSUE TITLE
Desarrollo de Módulo para almacenamiento de documentos

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente_v2#13]
Desarrollar las funcionalidades asociadas al almacenamiento de documentos de resoluciones.

**Criterio de aceptación**

- [x] Commit en rama feat con cambios realizados para API MID.
- [x] Commit en rama feat con cambios realizados para el Cliente.
- [x] Pruebas Unitarias.
- [x] Pruebas Funcionales.
- [x] Despliegue en ambiente de pruebas.

**Comment by jupmorenor** [comment]
Se implementó el consumo del gestor documental para registro y recuperación de documentos en formato pdf. Al expedir una resolución esta es almacenada en Nuxeo por medio del gestor documental y este documento se encuentra disponible para su consulta por medio del enlace que lo identifica.
