### ISSUE TITLE
Ajustes solicitados por asistentes decanatura

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#140]
Se requiere ajustar reporte de información financiera de cada una de las resoluciones (Excel) y establecer una plantilla para cargue masivo de RP's

**Especificaciones técnicas**

- El último despliegue se encuentra en la rama release con los ajustes realizados en la issue #137

**Sub Tareas**

- [x] En el reporte descargable en formato excel encontrado en cada una de las resoluciones, añadir los rubros desagregados por docente.
- [x] Establecer un archivo de carge de datos de RP´s que relacionen los docentes por facultad.

**Criterios de aceptación**

- [x] Comentario del issue con el archivo de cargue de RP´s propuestos.
- [x] El reporte formato excel muestra los rubros desagregados por docente y resolución.

**Requerimientos**

- [x] Ninguna

**Dependencias**

- Titán

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se actualiza el excel que se genera al momento de realizar una resolución de vinculación. Es importante resaltar que este informe solo puede ser generado al momento de seleccionar los docentes que harán parte de la resolución de vinculación

**Comment by diagutierrezro** [comment]
Se proponen los siguientes [formatos ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/diagutierrezr_udistrital_edu_co/Egk0fHyHX4lAuP6bmJNcCtYBau_8rsJbqONrIArH97VKYw?e=DyPlKt) para el cargue de RPs, hay un formato por cada dependencia para asegurar que se ponga el codigo correcto de cada una de estas.

**Comment by diagutierrezro** [comment]
Para el cargue de la información de los RP es necesario realizar una consulta usando el numero de resolución, vigencia y dependencia para poder saber el id de la resolución y poder conocer el campo en el que se hará el cargue
