### ISSUE TITLE
Reporte de financiera para definición de RP's

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#143]
Se requiere realizar reporte a los asistentes de decanatura para que estos puedan ser enviados a financiera y se generen los respectivos RP´s

**Especificaciones técnicas**

- El último despliegue se encuentra en la rama release con los ajustes realizados en las issue #137 y #140

**Sub Tareas**

- [x] En el menú añadir una opción "Reporte Financiera".
- [x] Añadir submenú "Consolidado de rubros por resolución"
- [x] Agregar un formulario que permita filtrar por resolución, tipo de vinculación y facultad.
- [x] Generar reporte en excel con los datos actualmente establecidos en el [reporte](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/cerochac_udistrital_edu_co/EX9tl5sshRBHuobTD6e8YekBB_cbaxTBjokp3Lz0lZdijQ?e=wqeI9D)
- [x] Adicionar los campos de: nombre del docente, CDP y facultad.

**Criterios de aceptación**

- [x] Se evidencia una nueva sección en el aplicativo.
- [x] Se observan los filtros definidos.
- [x] Se genera reporte con los datos necesarios y se descarga en formato excel.

**Requerimientos**

- [x] Ninguna

**Dependencias**

- Titán

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se adjunta documento de ejemplo de un reporte generado para una resolución de HCP en la facultad de ingenieria 
[reporte_financiera_607_2023 (2).csv](https://github.com/udistrital/resoluciones_cliente_v2/files/11985421/reporte_financiera_607_2023.2.csv)
