### ISSUE TITLE
Documento Diagnóstico Final

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#193]
Se requiere realizar el documento final "Diagnóstico" para todos las funcionalidades desarrolladas y por desarrollar en Resoluciones v2.

**Especificaciones técnicas**

- El formato del informe diagnóstico se encuentra en: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcEzaU-TYfNMpdLTB7j9u5IB-pa9uKfFzPSdI-ANpHqThA?e=1l6H4s.

**Sub Tareas**

- [x] Con base en el formatos propuesto desarrollar el informe.

**Criterios de aceptación**

- [x] Se genera un diagnóstico final sobre los proyectos llevados a cabo en Resoluciones v2.

**Requerimientos**

- [X] Formato para desarrollar.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by diagutierrezro** [comment]
Se crea el documento de [diganostico final ](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/diagutierrezr_udistrital_edu_co/EXXrbdLD1INEnIM8P1nRkmcBbIP6EJKgwUpjckyV817_YA?e=vSMnOA)

**Comment by milo19980525** [comment]
Por favor verificar la ortografía.

En limitaciones se debe mencionar que las resoluciones son incrementales en el tiempo, por lo que no se pueden hacer resoluciones por 3 semanas intermedias, serían solo las tres semanas finales.

Como prospectiva se pueden agregar las que se tenían planeadas anteriormente:

●	Versionamiento de plantillas
o	Descripción: Permitir la modificación de plantillas por medio de versiones.
o	Propuesta de desarrollo: Revisar y guiarse con la forma en que se hace el versionamiento del calendario académico en SGA.
o	Tiempo estimado: 5 semanas

●	Resoluciones de otro tipo (generales)
o	Descripción: Desarrollar un módulo que permita la generación de diferentes tipos de resoluciones y almacenar  datos específicos como tablas y cuadros.
o	Propuesta de desarrollo: Se propone agregar una columna en la tabla ComponenteResolucion de tipo json para almacenar información de tablas en cada artículo o parágrafo. En el cliente agregar una funcionalidad al formulario de la resolución para agregar tablas definidas por el usuario en cada artículo y/o parágrafo. Los textos de la resolución como consideraciones, artículos y parágrafos si se pueden seguir almacenando en el modelo existente. Los nuevos tipos de resolución deberán manejarse por separado en la API de parámetros.
o	Tiempo estimado: 6 semanas
●	Notificación de usuarios y docentes:
o	Descripción: implementación de notificaciones entre usuarios
o	Propuesta de desarrollo: enviar notificaciones a un usuario cuando hay nuevas resoluciones en el módulo que usa, por ejemplo, al enviar a revisión una resolución, notificar al usuario de la oficina de docencia. Por otro lado, enviar un correo de notificación a los docentes que han sido vinculados en una resolución que ha sido expedida.
o	Tiempo estimado: 3 semanas
●	Usuario de consulta
o	Descripción: habilitar usuario y rol con permiso solamente de consulta de las resoluciones
o	Propuesta de desarrollo: limitar con condiciones las acciones que se permite hacer al usuario basándose en el rol que tenga asignado (ponerse de acuerdo con el área de arquitectura para darle nombre a este rol)
o	Tiempo estimado: 2 semanas

**Comment by diagutierrezro** [comment]
Se realiza el ajuste indicado en el documento.

**Comment by milo19980525** [comment]
@diagutierrezro buen trabajo.
