### ISSUE TITLE
Despliegue en ambiente de pruebas

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente_v2#2]
Realizar el despliegue en ambiente de pruebas de las APIs MID y CRUD y el nuevo cliente de resoluciones.

**Criterios de aceptación**

- [x] check-list para despliegue de APIs.
- [x] despliegue API MID en preprod.
- [x] despliegue API CRUD en preprod.
- [x] despliegue Cliente en preprod.

**Comment by jupmorenor** [comment]
Se relacionan a continuación las checklist para cada uno de los repositorios:

1. Resoluciones Crud v2:
https://docs.google.com/document/d/18RNBpOt1xBFjNodNuxAwfzxIFFDTE6QE/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true

2. Resoluciones Mid v2:
https://docs.google.com/document/d/10ScYtutkDLSeE5W6vklanQjT5TxHLE8f/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true

3. Resoluciones cliente v2:
https://docs.google.com/document/d/1TsM4Mdj51fMmcDiUVF1GXr2yAl1nuFm4/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true
