### ISSUE TITLE
Pruebas de carga y seguridad

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente_v2#41]
Solicitar pruebas de carga y seguridad para nuevo resoluciones (V2) y realizar las correcciones correspondientes.

- [x] Solicitud de pruebas de C y S.
- [x] Corrección de errores.

**Comment by a52290451** [comment]
Se realiza solicitud de pruebas de C y S en el siguiente kanban:
https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=47088

**Comment by a52290451** [comment]
Se reciben resultados de las pruebas de C y S el 23/05/2022 y se inicia con la corrección de errores.

**Comment by jupmorenor** [comment]
Se abordaron y corrigieron las siguientes observaciones recibidas en los resultados de las pruebas de carga y seguridad:

- [ ] Ajuste de petición de carga horaria para que no envié parámetros undefined en módulo de vinculación.
- [ ] Ajuste del campo Fecha de expedición en módulo de expedición.
- [ ] Solo permitir peticiones para el dominio udistrital en las apis en prod.
- [ ] Actualización de dependencias para reducir vulnerabilidades (para reducir todas las vulnerabilidades se requiere cambiar angular a la ultima versión existente).
- [ ] Color del texto en los campos de filtro que tienen incluidas las tablas.
- [ ] Ajuste de ortografía en algunas palabras.
- [ ] Errores que no permitían la generación de documentos pdf
- [ ] Limitar valores de Ids en peticiones GET a números mayores a cero.

Se está gestionando la solución a las siguientes observaciones:
- Error 500 al cerrar la sesión

Las siguientes observaciones quedan pendientes:
- Implementación de *guards* para limitar el acceso a los diferentes módulos (depende de generación de lineamientos).
- Controlar que el cuerpo de las peticiones POST tengan contenido válido en las APIs
