### ISSUE TITLE
Creación de mockups para módulo de trazabilidad

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente_v2#47]
Se requiere crear los diferentes mockups asociados al módulo de trazabilidad de resoluciones, contemplando la posibilidad de visualizar la creación y modificaciones de una resolución.

**Criterios de aceptación**

- [x] Mockups del módulo

**Comment by a52290451** [comment]
Se realiza solicitud de validación y aprobación de Mockups por parte del usuario

**Comment by jupmorenor** [comment]
Se descarta el desarrollo de este módulo en favor de un reporte por medio de Knowage para la sección de presupuesto.
