### ISSUE TITLE
Casos de prueba en Resoluciones V2 según lo indicado por los usuarios.

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente_v2#50]
Se debe revisar si se requiere sincronización de datos para realizar pruebas. Si es el caso, se debe montar la solicitud a los DBAs:

- BD origen: udistrital_core_dv 
- Esquema: Administrativa 
- Ambiente: producción

- BD destino: udistrital_administrativa
- Esquema: resoluciones_new
- Ambiente: pruebas

Posteriormente, se requieren evaluar casos de prueba en resoluciones de acuerdo a lo compartido por parte del usuarios (2 y 3): https://github.com/udistrital/resoluciones_cliente_v2/issues/48

**Nota:** generar documento con casos de prueba.

**Comment by jupmorenor** [comment]
Se descarta sincronización de datos para trabajar con registros nuevos creados a partir del estado disponible en el esquema administrativa en ambiente de pruebas.
