### ISSUE TITLE
Documentación y entrega de resoluciones V2

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_cliente_v2#54]
Se requiere registrar la documentación asociada a resoluciones V2 (planeación, modelo de datos, historias de usuario, diagramas, modulos, funcionalidades, manuales de usuarios, videotutoriales, pruebas realizadas, etc), junto con acta de aceptación de  entregable debidamente diligenciada y firmada por las partes involucradas.

Nota: para el documento final, utilizar el siguiente formato:
[Plantilla - Diagnostico Final por sistema.docx](https://github.com/udistrital/resoluciones_cliente_v2/files/9087666/Plantilla.-.Diagnostico.Final.por.sistema.docx)

**Comment by jupmorenor** [comment]
Se realiza informe de diagnostico final de lo desarrollado en Resoluciones v2 detallando su estado al momento de la entrega:

[Documento](https://docs.google.com/document/d/1N8e4PkG55xQU883fJg7LFWiA4W1fMlaA/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true)

**Comment by a52290451** [comment]
Se valida y aprueba documentación final asociada a Resoluciones V2
