### ISSUE TITLE
Cuadro desagregado vinculaciones docente

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#63]
Teniendo en cuenta el [issue 19](https://github.com/udistrital/resoluciones_cliente_v2/issues/19) y lo conversado en el planning, realizar las siguientes tareas:

- [x] Revisar y comparar el formato de las tablas esperado y el que se está desplegando actualmente.
- [x] Corrección del formato en las tablas que presentan inconsistencias.
- [x] Revisar de cálculo en los cuadros desagregados de posgrados.

**Comment by jupmorenor** [comment]
- [ ] Pregrado - HCH - vinculación
- [ ] Pregrado - HCH - adición
- [ ] Pregrado - HCH - reducción
- [ ] Pregrado - HCH - cancelación
- [ ] Pregrado - HCP/TCO/MTO - vinculación
- [ ] Pregrado - HCP/TCO/MTO - adición
- [ ] Pregrado - HCP/TCO/MTO - reducción
- [ ] Pregrado - HCP/TCO/MTO - cancelación
- [ ] Posgrado - HCH - vinculación
- [ ] Posgrado - HCH - adición
- [ ] Posgrado - HCH - reducción
- [ ] Posgrado - HCH - cancelación
- [ ] Posgrado - HCP - vinculación
- [ ] Posgrado - HCP - adición
- [ ] Posgrado - HCP - reducción
- [ ] Posgrado - HCP - cancelación

**Comment by jupmorenor** [comment]
Se ha hecho la revisión del formato de las tablas de vinculación y se ha observado que las tablas de HCH tanto de pregrado como posgrado requieren ajustes importantes del formato.

**Comment by jupmorenor** [comment]
Se realizó ajuste para que al hacer los cálculos del desagregado para posgrados se utilice las horas semestrales y no semanales multiplicadas por las semanas.
