### ISSUE TITLE
Pruebas funcionales

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#67]
Se debe registrar el resultado de las pruebas funcionales asociadas a los módulos o funciones ajustadas y/o desarrolladas.

- [x] Documento o comentario que evidencie la realización de pruebas funcionales en el sistema.

**Comment by jupmorenor** [comment]
Se realizaron pruebas funcionales sobre todas las funciones del sistema, se registró el resultado inicial de estas pruebas en el siguiente documento: [link del documento](https://docs.google.com/spreadsheets/d/177TjIe4Wy3nhM2mPmoI2bkikmT33Golv/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true)

Adicionalmente, en el [documento de hallazgos](https://docs.google.com/spreadsheets/d/1-htT9-wXuy4G6rajSptqZ6mxscQ6_E-Z/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true) se detallan las fallas encontradas durante la realización de las pruebas. 

Hay algunas pruebas que no se han podido realizar debido a que dependen de la corrección de alguno de los hallazgos.

**Comment by jupmorenor** [comment]
Una vez aplicadas las correcciones pertinentes de acuerdo a los hallazgos #93 realizados parcialmente, se realizan las pruebas funcionales restantes. (ver documento actualizado)
