### ISSUE TITLE
Despliegue a producción

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#68]
Se requiere listar los elementos necesarios para salir a producción con las APIs del sistema y el cliente, así como registrar la trazabilidad de las solicitudes que se realicen.

Se despliega en producción el desarrollo asociado a la corrección de cuadro desagregado docente, lógica de filtrado y corrección de funcionalidades.

Criterios de aceptación

- [x]  Checklist de salida a producción por cada API y el cliente.
- [x]  Trazabilidad de peticiones y commits para salida a producción.
- [x]  Estabilización del sistema en producción.

**_**Nota: Tomar como ejemplo el siguiente checklist https://docs.google.com/document/d/1iUi8PSMeUyS-OxGH_mgSwSSs_ZAcYYUq/edit?usp=share_link&ouid=100698401433907561666&rtpof=true&sd=true**_**

**Comment by jupmorenor** [comment]
Se elaboran documentos checklist para salida a producción:

- [Resoluciones Cliente v2](https://docs.google.com/document/d/1mxJdDG8H_NfkZVEzcHeytSy016L0U7MZ/edit?usp=share_link&ouid=115705338596905688240&rtpof=true&sd=true) 
- [Resoluciones MID v2](https://docs.google.com/document/d/11n0Fir-waAwUaBG2PIWzSjhuviiJu1ZD/edit?usp=share_link&ouid=115705338596905688240&rtpof=true&sd=true)
- [Resoluciones CRUD v2](https://docs.google.com/document/d/16yp9mNJs5mnprr8nNx8ySqISjO5WyfyJ/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true)

**Comment by jupmorenor** [comment]
Se realizaron ajustes de acuerdo a hallazgos en ambiente de producción en https://github.com/udistrital/resoluciones_cliente_v2/issues/100
