### ISSUE TITLE
Versionamiento de plantillas

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#79]
- [x] Desarrollar la visualización para el versionamiento de plantillas  consumiendo los servicios asociados a estas ya implementados.

**Comment by jupmorenor** [comment]
Se optó por desarrollar una funcionalidad de copia de plantillas, en lugar de una de versionamiento como se había planteado inicialmente en #54. De esta manera se evita modificar el modelo de datos y hacer modificaciones muy grandes al código en las APIs sin dejar de proveer la facilidad en el manejo de las plantillas.
