### ISSUE TITLE
Definición de flujo de notificaciones

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#89]
Establecer el flujo que se deben seguir en las notificaciones mediante un diagrama de actividades.

**Criterios de aceptación**

- [x] Definir condiciones de acción de notificación necesaria (disparador) por actor (rol).
- [x] Definir las fases o etapas en las que esas condiciones se dan.
- [x] Relacionar lo anterior en un diagrama de actividades.

**Comment by jupmorenor** [comment]
Se establece que la condición que dispara la notificación es el cambio de estado de las resoluciones, se ha dividido el proceso en fases de la siguiente manera:

## FASE 1
### Submódulo Gestión de Resoluciones
rol: ASISTENTE_DECANATURA
acción: Enviar resolución a revisión
notificar a: ASISTENTE_DOCENCIA, DECANO


## FASE 2
### Submódulo Aprobación de Resoluciones
rol: ASISTENTE_DOCENCIA, DECANO
acción: Rechazar resolución
notificar a: ASISTENTE_DECANATURA

rol: ASISTENTE_DOCENCIA, DECANO
acción: Aprobar resolución
notificar a: DECANO


## FASE 3
### Submódulo Administración de Resoluciones
rol: DECANO
acción: Expedir resolución
notificar a: Docentes relacionados

Se adjunta diagrama de actividades:
![Notificaciones](https://user-images.githubusercontent.com/11802554/214691999-31d0fa7b-8dc1-482e-9669-45675c73682b.png)
