### ISSUE TITLE
Hallazgos 16-12-2022

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_cliente_v2#93]
Ajustar las siguientes tareas para poder terminar las pruebas funcionales o validarlas:

**Plantillas**
- [x] Revisar las plantillas que quedan con dependenciaId:0.

**Administración**
- [x] Revisar la carga de resoluciones al ser expedidas.

**Vinculaciones**
- [x] Para las adiciones y reducciones en las vinculaciones, probar con una respuesta ficticia del semáforo de administrativa que funcione (Vacía y con el cargo).
- [x] Ajustar el campo de "Tipo documento" en el informe PDF.

**Resoluciones**
- [x] Cambiar el mensaje de error al no encontrar un docente por uno de alerta o informativo.
- [x] Desarrollar lógica para poder filtrar por el último estado de la resolución.

**Comment by jupmorenor** [comment]
Para filtrar el ultimo estado de la resolución se requiere ajustar la información por medio de una query en SQL en la que se ajuste el campo `activo` a `false`.

**Comment by jupmorenor** [comment]
- Se aplicó una sentencia SQL sobre el esquema de datos para desactivar las resoluciones con estado `Anulada` y otro para desactivar los estados de las resoluciones diferentes al estado mas reciente.
